/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MockValidatorsVoterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addGauge"
      | "claimBribes"
      | "claimable"
      | "gaugeToBribe"
      | "gauges"
      | "isAlive"
      | "isWhitelistedToken"
      | "killGauge"
      | "length"
      | "musd"
      | "pendingBribes"
      | "seedBribe"
      | "vote"
      | "whitelistToken"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addGauge",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimBribes",
    values: [AddressLike[], AddressLike[][], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gaugeToBribe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gauges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAlive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "killGauge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(functionFragment: "musd", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingBribes",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "seedBribe",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "whitelistToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addGauge", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimBribes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gaugeToBribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gauges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAlive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "killGauge", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "musd", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingBribes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seedBribe", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "whitelistToken",
    data: BytesLike
  ): Result;
}

export interface MockValidatorsVoter extends BaseContract {
  connect(runner?: ContractRunner | null): MockValidatorsVoter;
  waitForDeployment(): Promise<this>;

  interface: MockValidatorsVoterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addGauge: TypedContractMethod<
    [gauge: AddressLike, bribe: AddressLike],
    [void],
    "nonpayable"
  >;

  claimBribes: TypedContractMethod<
    [bribes: AddressLike[], arg1: AddressLike[][], arg2: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimable: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  gaugeToBribe: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  gauges: TypedContractMethod<[index: BigNumberish], [string], "view">;

  isAlive: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isWhitelistedToken: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  killGauge: TypedContractMethod<[gauge: AddressLike], [void], "nonpayable">;

  length: TypedContractMethod<[], [bigint], "view">;

  musd: TypedContractMethod<[], [string], "view">;

  pendingBribes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  seedBribe: TypedContractMethod<
    [gauge: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  vote: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike[], arg2: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  whitelistToken: TypedContractMethod<
    [token: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addGauge"
  ): TypedContractMethod<
    [gauge: AddressLike, bribe: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimBribes"
  ): TypedContractMethod<
    [bribes: AddressLike[], arg1: AddressLike[][], arg2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "gaugeToBribe"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "gauges"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isAlive"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelistedToken"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "killGauge"
  ): TypedContractMethod<[gauge: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "length"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "musd"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingBribes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "seedBribe"
  ): TypedContractMethod<
    [gauge: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike[], arg2: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "whitelistToken"
  ): TypedContractMethod<[token: AddressLike], [void], "nonpayable">;

  filters: {};
}
