/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as byNdVaultSol from "./ByNdVault.sol";
export type { byNdVaultSol };
import type * as byNdVoterSol from "./ByNdVoter.sol";
export type { byNdVoterSol };
import type * as mocks from "./mocks";
export type { mocks };
export type { ByNdStaking } from "./ByNdStaking";
export type { VeBYND } from "./VeBYND";
