/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ByNdVoter__factory } from "./ByNdVoter__factory";
export { IBoostVoter__factory } from "./IBoostVoter__factory";
