/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface ByNdVoterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_BPS"
      | "boostVoter"
      | "bountyBps"
      | "castVotes"
      | "currentEpoch"
      | "epochDuration"
      | "epochHarvested"
      | "epochLocksExtended"
      | "epochVoted"
      | "fetchLiveGauges"
      | "gauges"
      | "getBribeForGauge"
      | "getGaugeCount"
      | "getPendingIncentives"
      | "governance"
      | "harvestAndDistribute"
      | "isGaugeAlive"
      | "lastVoteTimestamp"
      | "managedTokenId"
      | "markLocksExtended"
      | "minHarvestThreshold"
      | "musd"
      | "owner"
      | "renounceOwnership"
      | "resetEpochClock"
      | "setBoostVoter"
      | "setBountyBps"
      | "setEpochDuration"
      | "setGauges"
      | "setManagedTokenId"
      | "setMinHarvestThreshold"
      | "staking"
      | "timeUntilNextVote"
      | "transferGovernance"
      | "transferOwnership"
      | "voteWindow"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GaugesUpdated"
      | "Harvested"
      | "LocksExtendedMarked"
      | "MinThresholdUpdated"
      | "OwnershipTransferred"
      | "VotesCast"
  ): EventFragment;

  encodeFunctionData(functionFragment: "MAX_BPS", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "boostVoter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "bountyBps", values?: undefined): string;
  encodeFunctionData(functionFragment: "castVotes", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "currentEpoch",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "epochHarvested",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochLocksExtended",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "epochVoted",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fetchLiveGauges",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "gauges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getBribeForGauge",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getGaugeCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPendingIncentives",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "governance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "harvestAndDistribute",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isGaugeAlive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lastVoteTimestamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "managedTokenId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "markLocksExtended",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minHarvestThreshold",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "musd", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetEpochClock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setBoostVoter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setBountyBps",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setEpochDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setGauges",
    values: [
      AddressLike[],
      AddressLike[],
      string[],
      BigNumberish[],
      AddressLike[][]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setManagedTokenId",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinHarvestThreshold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "staking", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "timeUntilNextVote",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferGovernance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "voteWindow",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "MAX_BPS", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "boostVoter", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bountyBps", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "castVotes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "currentEpoch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochHarvested",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "epochLocksExtended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "epochVoted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fetchLiveGauges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gauges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBribeForGauge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getGaugeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPendingIncentives",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "governance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "harvestAndDistribute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isGaugeAlive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lastVoteTimestamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "managedTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "markLocksExtended",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minHarvestThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "musd", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetEpochClock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBoostVoter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setBountyBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEpochDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setGauges", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setManagedTokenId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinHarvestThreshold",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "staking", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "timeUntilNextVote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "voteWindow", data: BytesLike): Result;
}

export namespace GaugesUpdatedEvent {
  export type InputTuple = [count: BigNumberish];
  export type OutputTuple = [count: bigint];
  export interface OutputObject {
    count: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HarvestedEvent {
  export type InputTuple = [
    epoch: BigNumberish,
    keeper: AddressLike,
    totalMUSD: BigNumberish,
    keeperBounty: BigNumberish,
    stakerShare: BigNumberish
  ];
  export type OutputTuple = [
    epoch: bigint,
    keeper: string,
    totalMUSD: bigint,
    keeperBounty: bigint,
    stakerShare: bigint
  ];
  export interface OutputObject {
    epoch: bigint;
    keeper: string;
    totalMUSD: bigint;
    keeperBounty: bigint;
    stakerShare: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LocksExtendedMarkedEvent {
  export type InputTuple = [epoch: BigNumberish, keeper: AddressLike];
  export type OutputTuple = [epoch: bigint, keeper: string];
  export interface OutputObject {
    epoch: bigint;
    keeper: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinThresholdUpdatedEvent {
  export type InputTuple = [newThreshold: BigNumberish];
  export type OutputTuple = [newThreshold: bigint];
  export interface OutputObject {
    newThreshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotesCastEvent {
  export type InputTuple = [epoch: BigNumberish, gaugeCount: BigNumberish];
  export type OutputTuple = [epoch: bigint, gaugeCount: bigint];
  export interface OutputObject {
    epoch: bigint;
    gaugeCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ByNdVoter extends BaseContract {
  connect(runner?: ContractRunner | null): ByNdVoter;
  waitForDeployment(): Promise<this>;

  interface: ByNdVoterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_BPS: TypedContractMethod<[], [bigint], "view">;

  boostVoter: TypedContractMethod<[], [string], "view">;

  bountyBps: TypedContractMethod<[], [bigint], "view">;

  castVotes: TypedContractMethod<[], [void], "nonpayable">;

  currentEpoch: TypedContractMethod<[], [bigint], "view">;

  epochDuration: TypedContractMethod<[], [bigint], "view">;

  epochHarvested: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  epochLocksExtended: TypedContractMethod<
    [arg0: BigNumberish],
    [boolean],
    "view"
  >;

  epochVoted: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  fetchLiveGauges: TypedContractMethod<
    [],
    [
      [string[], string[], bigint[]] & {
        gaugeAddrs: string[];
        brideAddrs: string[];
        claimableAmounts: bigint[];
      }
    ],
    "view"
  >;

  gauges: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        gauge: string;
        bribe: string;
        name: string;
        weightBps: bigint;
      }
    ],
    "view"
  >;

  getBribeForGauge: TypedContractMethod<[gauge: AddressLike], [string], "view">;

  getGaugeCount: TypedContractMethod<[], [bigint], "view">;

  getPendingIncentives: TypedContractMethod<[], [bigint], "view">;

  governance: TypedContractMethod<[], [string], "view">;

  harvestAndDistribute: TypedContractMethod<[], [void], "nonpayable">;

  isGaugeAlive: TypedContractMethod<[gauge: AddressLike], [boolean], "view">;

  lastVoteTimestamp: TypedContractMethod<[], [bigint], "view">;

  managedTokenId: TypedContractMethod<[], [bigint], "view">;

  markLocksExtended: TypedContractMethod<[], [void], "nonpayable">;

  minHarvestThreshold: TypedContractMethod<[], [bigint], "view">;

  musd: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  resetEpochClock: TypedContractMethod<[], [void], "nonpayable">;

  setBoostVoter: TypedContractMethod<
    [_voter: AddressLike],
    [void],
    "nonpayable"
  >;

  setBountyBps: TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;

  setEpochDuration: TypedContractMethod<
    [duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setGauges: TypedContractMethod<
    [
      _gauges: AddressLike[],
      _bribes: AddressLike[],
      _names: string[],
      _weightsBps: BigNumberish[],
      _tokens: AddressLike[][]
    ],
    [void],
    "nonpayable"
  >;

  setManagedTokenId: TypedContractMethod<
    [_tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinHarvestThreshold: TypedContractMethod<
    [threshold: BigNumberish],
    [void],
    "nonpayable"
  >;

  staking: TypedContractMethod<[], [string], "view">;

  timeUntilNextVote: TypedContractMethod<[], [bigint], "view">;

  transferGovernance: TypedContractMethod<
    [newGov: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  voteWindow: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "boostVoter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "bountyBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "castVotes"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "currentEpoch"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "epochHarvested"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "epochLocksExtended"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "epochVoted"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "fetchLiveGauges"
  ): TypedContractMethod<
    [],
    [
      [string[], string[], bigint[]] & {
        gaugeAddrs: string[];
        brideAddrs: string[];
        claimableAmounts: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "gauges"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint] & {
        gauge: string;
        bribe: string;
        name: string;
        weightBps: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBribeForGauge"
  ): TypedContractMethod<[gauge: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getGaugeCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPendingIncentives"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "governance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "harvestAndDistribute"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isGaugeAlive"
  ): TypedContractMethod<[gauge: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "lastVoteTimestamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "managedTokenId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "markLocksExtended"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "minHarvestThreshold"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "musd"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "resetEpochClock"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBoostVoter"
  ): TypedContractMethod<[_voter: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setBountyBps"
  ): TypedContractMethod<[bps: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setEpochDuration"
  ): TypedContractMethod<[duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setGauges"
  ): TypedContractMethod<
    [
      _gauges: AddressLike[],
      _bribes: AddressLike[],
      _names: string[],
      _weightsBps: BigNumberish[],
      _tokens: AddressLike[][]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setManagedTokenId"
  ): TypedContractMethod<[_tokenId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinHarvestThreshold"
  ): TypedContractMethod<[threshold: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "staking"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timeUntilNextVote"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferGovernance"
  ): TypedContractMethod<[newGov: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "voteWindow"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "GaugesUpdated"
  ): TypedContractEvent<
    GaugesUpdatedEvent.InputTuple,
    GaugesUpdatedEvent.OutputTuple,
    GaugesUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Harvested"
  ): TypedContractEvent<
    HarvestedEvent.InputTuple,
    HarvestedEvent.OutputTuple,
    HarvestedEvent.OutputObject
  >;
  getEvent(
    key: "LocksExtendedMarked"
  ): TypedContractEvent<
    LocksExtendedMarkedEvent.InputTuple,
    LocksExtendedMarkedEvent.OutputTuple,
    LocksExtendedMarkedEvent.OutputObject
  >;
  getEvent(
    key: "MinThresholdUpdated"
  ): TypedContractEvent<
    MinThresholdUpdatedEvent.InputTuple,
    MinThresholdUpdatedEvent.OutputTuple,
    MinThresholdUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "VotesCast"
  ): TypedContractEvent<
    VotesCastEvent.InputTuple,
    VotesCastEvent.OutputTuple,
    VotesCastEvent.OutputObject
  >;

  filters: {
    "GaugesUpdated(uint256)": TypedContractEvent<
      GaugesUpdatedEvent.InputTuple,
      GaugesUpdatedEvent.OutputTuple,
      GaugesUpdatedEvent.OutputObject
    >;
    GaugesUpdated: TypedContractEvent<
      GaugesUpdatedEvent.InputTuple,
      GaugesUpdatedEvent.OutputTuple,
      GaugesUpdatedEvent.OutputObject
    >;

    "Harvested(uint256,address,uint256,uint256,uint256)": TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;
    Harvested: TypedContractEvent<
      HarvestedEvent.InputTuple,
      HarvestedEvent.OutputTuple,
      HarvestedEvent.OutputObject
    >;

    "LocksExtendedMarked(uint256,address)": TypedContractEvent<
      LocksExtendedMarkedEvent.InputTuple,
      LocksExtendedMarkedEvent.OutputTuple,
      LocksExtendedMarkedEvent.OutputObject
    >;
    LocksExtendedMarked: TypedContractEvent<
      LocksExtendedMarkedEvent.InputTuple,
      LocksExtendedMarkedEvent.OutputTuple,
      LocksExtendedMarkedEvent.OutputObject
    >;

    "MinThresholdUpdated(uint256)": TypedContractEvent<
      MinThresholdUpdatedEvent.InputTuple,
      MinThresholdUpdatedEvent.OutputTuple,
      MinThresholdUpdatedEvent.OutputObject
    >;
    MinThresholdUpdated: TypedContractEvent<
      MinThresholdUpdatedEvent.InputTuple,
      MinThresholdUpdatedEvent.OutputTuple,
      MinThresholdUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "VotesCast(uint256,uint256)": TypedContractEvent<
      VotesCastEvent.InputTuple,
      VotesCastEvent.OutputTuple,
      VotesCastEvent.OutputObject
    >;
    VotesCast: TypedContractEvent<
      VotesCastEvent.InputTuple,
      VotesCastEvent.OutputTuple,
      VotesCastEvent.OutputObject
    >;
  };
}
