/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IBoostVoterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claimBribes"
      | "claimable"
      | "gaugeToBribe"
      | "gauges"
      | "isAlive"
      | "isWhitelistedToken"
      | "length"
      | "vote"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claimBribes",
    values: [AddressLike[], AddressLike[][], BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "claimable",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gaugeToBribe",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "gauges",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isAlive",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelistedToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "length", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, AddressLike[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "claimBribes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimable", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "gaugeToBribe",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gauges", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isAlive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelistedToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "length", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
}

export interface IBoostVoter extends BaseContract {
  connect(runner?: ContractRunner | null): IBoostVoter;
  waitForDeployment(): Promise<this>;

  interface: IBoostVoterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claimBribes: TypedContractMethod<
    [_bribes: AddressLike[], _tokens: AddressLike[][], _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;

  claimable: TypedContractMethod<[gauge: AddressLike], [bigint], "view">;

  gaugeToBribe: TypedContractMethod<[gauge: AddressLike], [string], "view">;

  gauges: TypedContractMethod<[index: BigNumberish], [string], "view">;

  isAlive: TypedContractMethod<[gauge: AddressLike], [boolean], "view">;

  isWhitelistedToken: TypedContractMethod<
    [token: AddressLike],
    [boolean],
    "view"
  >;

  length: TypedContractMethod<[], [bigint], "view">;

  vote: TypedContractMethod<
    [
      _tokenId: BigNumberish,
      _gaugeVote: AddressLike[],
      _weights: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claimBribes"
  ): TypedContractMethod<
    [_bribes: AddressLike[], _tokens: AddressLike[][], _tokenId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimable"
  ): TypedContractMethod<[gauge: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "gaugeToBribe"
  ): TypedContractMethod<[gauge: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "gauges"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "isAlive"
  ): TypedContractMethod<[gauge: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isWhitelistedToken"
  ): TypedContractMethod<[token: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "length"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [
      _tokenId: BigNumberish,
      _gaugeVote: AddressLike[],
      _weights: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
